name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Clone repository
        uses: actions/checkout@v6
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/go/bin/
            ~/go/pkg/mod/
          key: ${{hashFiles('book.toml', '.github/workflows/deploy.yml')}}
      - name: Install mdbook & plugins
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |-
          cargo install --git https://github.com/sspaeti/mdBook --branch adding_frontmatter --features frontmatter mdbook
          cargo install --git https://github.com/saylesss88/mdbook-rss-feed --rev 1cdbba0 --features atom,json-feed
      - name: Build book
        run: mdbook build
      - name: Generate sitemap
        uses: actions/github-script@v9
        env:
          BASE_URL: https://${{github.event.repository.owner.name}}.github.io/${{github.event.repository.name}}
        with:
          script: |-
            const { readFileSync, writeFileSync } = require('fs');
            const { relative } = require('path');

            const base = process.env.BASE_URL.toLocaleLowerCase();
            const globs = ['src/**/*.md', '!src/SUMMARY.md'].join('\n');
            const urls = await glob.create(globs)
              .then(g => g.glob()).then(files => {
                return files.sort((a, b) => {
                  if (a.endsWith('index.md')) return 1;
                  if (b.endsWith('index.md')) return -1;
                  return b.localeCompare(a);
                }).map(f => {
                  const lines = readFileSync(f, 'utf8').split('\n');
                  const html = relative('src', f).replace('.md', '.html');
                  const lastmod = lines[4].match(/^date: (.+)$/)[1];
                  return '<url>\n' +
                    `  <loc>${base}/${html}</loc>\n` +
                    `  <lastmod>${lastmod}</lastmod>\n` +
                    '</url>';
                });
              });

            const sitemap = '<?xml version="1.0" encoding="UTF-8"?>\n' +
              '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
              urls.join('\n') +
              '</urlset>';
            writeFileSync('book/sitemap.xml', sitemap);
            core.info(`Generated sitemap.xml with ${urls.length} URLs.`);
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: book
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
